FROM ubuntu:bionic
RUN apt-get update && apt-get install -y build-essential manpages-dev vim git-core python3 python3-pip python3-dev
RUN pip3 install numpy matplotlib
ARG git_user='Tianxiang'
ARG git_email='TSu@slb.com'
RUN git config --global user.name ${git_user} && git config --global user.email ${git_email}
ARG TZ='America/New_York'
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y gitk
ARG UID=1001
ARG GID=1001
ARG UNAME=TSu
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
USER $UNAME
USER TSu
